site_name: DEV-000
site_description: The Complete Introduction to Development
site_author: Trent Fellbootman
site_url: https://TODO
repo_name: Trent-Fellbootman/dev000
repo_url: https://github.com/Trent-Fellbootman/dev000
edit_uri: blob/main/docs

docs_dir: docs
theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - Home:
    - About: index.md
    - Course Outline: outline.md
