site_name: DEV-000
site_description: The Complete Introduction to Development
site_author: Trent Fellbootman
site_url: https://TODO
repo_name: Trent-Fellbootman/dev000
repo_url: https://github.com/Trent-Fellbootman/dev000
edit_uri: blob/main/docs

docs_dir: docs
theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home:
    - About: index.md
    - Course Outline: outline.md

  - "Module 0: The Developer's Mindset":
    - Introduction: developer-mindset/index.md
    - developer-mindset/abstraction.md
    - developer-mindset/hierarchy.md
    - developer-mindset/standards.md
    - developer-mindset/conclusion.md
  - "Module 1: The Abstract Computer":
    - Introduction: abstract-computer/index.md
    - abstract-computer/why-abstraction.md
    - abstract-computer/isa.md
    - abstract-computer/memory-use-cases-stack-heap.md
    - abstract-computer/conclusion.md
  - "Module 2: Programming Languages":
    - Introduction: programming-languages/intro.md
